assignment:
  name: "{name}"
  class: "CS-UY 3224"
  hidden: true
  # Optionally specify the github classroom link
  # for students to get their repo.
  github_classroom_url: ""

  # Don't change these!
  unique_code: "{code}"
  pipeline_image: "registry.osiris.services/anubis/assignment/{code}"

  # Specify the importaint dates here
  date:
    release: "{now}"
    due: "{week_from_now}"
    grace: "{week_from_now}"

  # This description will be shown to the user on the Anubis website.
  description: |
    This is a very long description that encompases the entire assignment

  # Uncomment this section if you want to have question pools
  # These questions are purely additive. To delete a question, you will
  # need to manually edit the database. This is by design to prevent
  # a question assigned to a student from being changed to prevent
  # confusion.
  questions:
    - sequence: 1
      questions:
        - q: "What is 3*4?"
          a: "12"
        - q: "What is 3*2"
          a: "6"
    - sequence: 2
      questions:
        - q: "What is sqrt(144)?"
          a: "12"
