assignment:
  name: "{name}"
  class: "{course_code}"
  hidden: true

  # Optionally specify the github classroom link
  # for students to get their repo.
  #
  #  !! Remember to set the Custom repository
  #  !! prefix to {name}-{unique_code}
  #  !! when creating the assignment on
  #  !! Github Classroom
  github_classroom_url: ""

  # Don't change these!
  unique_code: "{unique_code}"
  pipeline_image: "registry.digitalocean.com/anubis/assignment/{unique_code}"

  # Specify the important dates here
  # * Remember! These are interpreted as America/New_York *
  date:
    release: "{now}"
    due: "{week_from_now}"
    grace: "{week_from_now}"

  # This description will be shown to the user on the Anubis website.
  description: |
    This is a very long description that encompases the entire assignment
