apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    component: api

spec:
  selector:
    matchLabels:
      app: api
  replicas: {{ .Values.api.replicas }}
  {{- if .Values.rollingUpdates }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  {{- end }}
  template:
    metadata:
      labels:
        app: api
    spec:
      # dnsPolicy: Default
      # nodeSelector:
      #   datacenter: sdc
      containers:
      - name: api
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: web
          containerPort: 5000
        env:
        - name: "DEBUG"
          value: {{- if .Values.debug }} "1"{{- else }} "0"{{- end }}
        - name: "MIGRATE"
          value: "1"
        - name: "DISABLE_ELK"
          value: "0"
        # Gunicorn workers
        - name: "WORKERS"
          value: {{ .Values.api.workers | quote }}
        {{- if .Values.api.gunicorn_options }}
        - name: "GUNICORN_OPTIONS"
          value: {{ .Values.api.gunicorn_options | quote }}
        {{- end }}
        - name: "SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: api
              key: secret-key
        - name: "OAUTH_CONSUMER_KEY"
          valueFrom:
            secretKeyRef:
              name: oauth
              key: consumer-key
        - name: "OAUTH_CONSUMER_SECRET"
          valueFrom:
            secretKeyRef:
              name: oauth
              key: consumer-secret
        - name: DB_HOST
          value: mariadb.mariadb.svc.cluster.local
        # sqlalchemy uri
        - name: "DATABASE_URI"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-uri
        - name: "REDIS_PASS"
          valueFrom:
            secretKeyRef:
              name: api
              key: redis-password
        - name: "THEIA_DOMAIN"
          value: {{ .Values.theia.proxy.domain | quote }}
        {{- if .Values.api.healthCheck }}
        livenessProbe:
          exec:
            command:
              - curl
              - http://localhost:5000/
          initialDelaySeconds: 10
          periodSeconds: 5
        {{- end }}

      # Mail container
      - name: smtp
        image: namshi/smtp

---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  namespace: {{ .Release.Namespace }}
  labels:
    job: db-migrate
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
    component: migrate
spec:
  backoffLimit: 4
  ttlSecondsAfterFinished: 30
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrate
        image: {{ .Values.api.image }}:{{ .Values.api.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["alembic", "upgrade", "head"]
        env:
        # sqlalchemy uri
        - name: "DATABASE_URI"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-uri
        - name: "REDIS_PASS"
          valueFrom:
            secretKeyRef:
              name: api
              key: redis-password

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  namespace: {{ .Release.Namespace }}
  labels:
    app: adminer
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: adminer
        image: adminer:latest
        env:
        - name: "ADMINER_DEFAULT_SERVER"
          value: "mariadb.mariadb.svc.cluster.local"
        ports:
        - name: adminer
          containerPort: 8080
        resources:
          limits:
            memory: "200Mi"
          requests:
            memory: "100Mi"

---
apiVersion: v1
kind: Service
metadata:
  name: anubis
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: api
  ports:
  - name: web
    port: 5000
    targetPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  namespace: {{ .Release.Namespace }}
  labels:
    app: adminer
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app: adminer
  ports:
  - name: adminer
    port: 5002
    targetPort: 8080

---
# Strip prefix /api
apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: strip-api
  namespace: {{ .Release.Namespace }}
  labels:
    app: anubis
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  stripPrefix:
    prefixes:
      - "/api"

---
# Public Ingress Route /api/public/*
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ingress.route.anubis.api.public
  namespace: {{ .Release.Namespace }}
  labels:
    app: api
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ .Values.domain }}`) && PathPrefix(`/api/`)
    middlewares:
    {{- if .Values.vpnOnly }}
    - name: whitelist-vpn
      namespace: traefik
    {{- end }}
    - name: strip-api
      namespace: {{ .Release.Namespace }}
    services:
    - name: anubis
      port: 5000
  tls:
    certResolver: tls
