### ELK stack
# - Elasticsearch
# - Logstash
# - Kibana

## Logstash
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: logstash
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: logstash
  template:
    metadata:
      labels:
        app.kubernetes.io/name: logstash
        ecosystem: elk
    spec:
      containers:
      - name: logstash
        image: {{ .Values.logstash.image }}:{{ .Values.logstash.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: web
          containerPort: 5000
        - name: api
          containerPort: 9600

---
apiVersion: v1
kind: Service
metadata:
  name: logstash
  namespace: anubis
  labels:
    app.kubernetes.io/name: logstash
spec:
  selector:
    app.kubernetes.io/name: logstash
  ports:
  - name: logstash
    protocol: UDP
    port: 5000
    targetPort: 5000
  - name: api
    port: 9600
    targetPort: 9600

---
