{{- if .Values.theia.enable }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: theia-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: theia
    component: proxy
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.theia.proxy.replicas }}
  {{- if .Values.rollingUpdates }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: theia
      component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name: theia
        component: proxy
    spec:
      containers:
      - name: proxy
        image: {{ .Values.theia.proxy.image }}:{{ .Values.theia.proxy.tag }}
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - name: http
          containerPort: 5000
        env:
        - name: "SECRET_KEY"
          valueFrom:
            secretKeyRef:
              name: api
              key: secret-key
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: api
              key: database-password
        - name: "DB_HOST"
          value: "mariadb.mariadb.svc.cluster.local"

---

apiVersion: v1
kind: Service
metadata:
  name: theia-proxy
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: theia
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  selector:
    app.kubernetes.io/name: theia
    component: proxy
  ports:
    - name: http-tcp
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: http-udp
      protocol: UDP
      port: 5000
      targetPort: 5000


---


{{- end }}
