debug: false
rollingUpdates: true
healthChecks: true
domain: "anubis.osiris.services"
vpnOnly: false
imagePullPolicy: "Always"

api:
  replicas: 3
  workers: 4
  datacenter: "mtc"
  gunicorn_options: "--capture-output --enable-stdio-inheritance --preload --timeout 30"
  image: "registry.osiris.services/anubis/api"
  tag: "latest"

static:
  replicas: 3
  image: "registry.osiris.services/anubis/static"
  tag: "latest"
  healthCheck: true

reaper:
  enable: true
  schedule: "*/5 * * * *"
  suspend: false

visuals:
  enable: true
  schedule: "*/5 * * * *"
  suspend: false

pipeline_api:
  replicas: 3
  workers: 2

web:
  replicas: 2
  image: "registry.osiris.services/anubis/web"
  tag: "latest"

logstash:
  image: "registry.osiris.services/anubis/logstash"
  tag: "latest"

rpc:
  default:
    replicas: 5    
  theia:
    replicas: 5    
  regrade:
    replicas: 5

theia:
  enable: true
  proxy:
    replicas: 10
    domain: "ide.anubis.osiris.services"
    image: "registry.osiris.services/anubis/theia-proxy"
    tag: "latest"
