env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - google
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: off
  require-jsdoc: off
  valid-jsdoc: off
  camelcase: off
  no-unused-vars: off
  react/display-name: off
  indent: ["error", 2]
  max-len: ["error", { "code": 120 }]
